### ISSUE TITLE
The right click action of blocks that drop something give the mask item instead of correct item

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/Ore-Stages#10]
This is something I know Darko has run into forever, and just has gone unnoticed and/or un-reported. When right clicking an ore sample (when they are supposed to see it/its not hidden) it is intended to drop a cluster, but it instead drops a rock.

Reference: https://github.com/Darkosto/SevTech-Ages/issues/854

**Comment by darkhax** [comment]
My current guess is that this issue is caused by the player for right clicking being null. Right clicking their block calls dropBlockAsItem, which fires the HarvestDropsEvent which I make use of. However, this event is fired by Forge using the harvesters thread. 
```java
chance = net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(drops, worldIn, pos, state, fortune, chance, false, harvesters.get());
```
Since no player has harvested the block, harvesters.get() would either be null or the wrong player.

**Comment by darkhax** [comment]
Not sure what the follow up is, but since this is another mod's issue, I will be closing this.
